# Generated by Django 3.2.3 on 2021-08-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('ingredients', models.TextField()),
                ('method', models.TextField()),
                ('vegetarian', models.BooleanField(default=False)),
                ('glutenfree', models.BooleanField(default=False)),
                ('nuts', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('number', models.IntegerField(max_length=200)),
            ],
        ),
    ]
