# Generated by Django 3.2.3 on 2021-08-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='placebo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='weight',
            name='number',
            field=models.IntegerField(),
        ),
    ]
