# Generated by Django 3.2.3 on 2021-08-07 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meals', '0004_weight_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
