# Generated by Django 3.2.3 on 2021-08-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_alter_meal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='totalCalories',
            field=models.IntegerField(null=True),
        ),
    ]
