# Generated by Django 3.2.3 on 2021-08-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0008_meal_totalcalories'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='dinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='lunch',
            field=models.BooleanField(default=False),
        ),
    ]
