# Generated by Django 3.2.3 on 2021-08-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0010_meal_pescatarian'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='lactose',
            field=models.BooleanField(default=False),
        ),
    ]
