# Generated by Django 3.2.3 on 2021-08-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0011_meal_lactose'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
    ]
