# Generated by Django 3.2.3 on 2021-08-27 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meals', '0012_meal_vegan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favMealID', to='meals.meal')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faveUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
