# Generated by Django 3.2.3 on 2021-08-31 00:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meals', '0018_alter_meal_favorited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='saved',
            field=models.ManyToManyField(blank=True, default=None, related_name='saveUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
