# Generated by Django 3.2.3 on 2021-09-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0021_restrictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='restrictions',
            name='dietRestr',
            field=models.CharField(choices=[('vegan', 'vegan'), ('vegetarian', 'vegetarian'), ('pescatarian', 'pescatarian'), ('gluten allergy', 'gluten allergy'), ('lactose intolerant', 'lactose intolerant'), ('nut allergy', 'nut allergy')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='weight',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
