# Generated by Django 3.2.3 on 2021-09-17 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0022_auto_20210917_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
