# Generated by Django 3.2.3 on 2021-09-17 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0023_alter_weight_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='time',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
