# Generated by Django 3.2.3 on 2021-09-17 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0024_alter_weight_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='weight',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
