# Generated by Django 3.2.3 on 2021-09-17 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0025_auto_20210917_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 17, 16, 46, 49, 882468)),
        ),
    ]
