# Generated by Django 3.2.3 on 2021-10-01 14:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meals', '0027_auto_20211001_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='lastMeal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lastMealViewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uInfo', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 1, 22, 32, 32, 315046)),
        ),
    ]
