# Generated by Django 3.2.3 on 2021-10-01 14:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0028_auto_20211001_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='lastMeal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lastMealViewed', to='meals.meal'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 1, 22, 34, 28, 729701)),
        ),
    ]
