# Generated by Django 3.2.3 on 2021-10-06 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0029_auto_20211001_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
