# Generated by Django 3.2.3 on 2021-10-08 01:38

from django.db import migrations
from django.apps import apps

def get_ingredients(apps_config, schema_editor):
    Meal = apps.get_model('meals','Meal')
    Ingredient = apps.get_model('meals','Ingredient')
    meals = Meal.objects.all()
    for meal in meals:
        ingredient_text = meal.ingredients
        str_ingredients = ingredient_text.split("\n")
        for ingredient in str_ingredients:
            ingredient_name = ingredient.strip()
            Ingredient.objects.create(name=ingredient_name, meal=meal)

class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0032_alter_useringredient_status'),
    ]

    operations = [
        migrations.RunPython(get_ingredients),
    ]
