# Generated by Django 3.2.3 on 2021-10-12 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0033_auto_20211008_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientMeal', to='meals.meal'),
        ),
    ]
