# Generated by Django 3.2.3 on 2021-10-15 02:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meals', '0035_auto_20211012_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='restrictions',
            field=models.ManyToManyField(blank=True, choices=[('vegan', 'vegan'), ('vegetarian', 'vegetarian'), ('pescatarian', 'pescatarian'), ('glutenfree', 'glutenfree'), ('lactose', 'lactose'), ('nuts', 'nuts')], default=None, related_name='restrictions_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
