# Generated by Django 3.2.3 on 2021-10-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0037_auto_20211015_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietRestr', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Restrictions',
        ),
    ]
