# Generated by Django 3.2.3 on 2021-10-27 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0038_auto_20211027_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restriction',
            old_name='dietRestr',
            new_name='description',
        ),
    ]
