# Generated by Django 3.2.3 on 2021-10-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0039_rename_dietrestr_restriction_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='glutenAllergy',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='lactoseIntolerant',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='nutAllergy',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='pescatarian',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='vegan',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='vegetarian',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='restrictions',
            field=models.ManyToManyField(blank=True, related_name='restrictions', to='meals.Restriction'),
        ),
    ]
