# Generated by Django 3.2.3 on 2021-10-27 13:09

from django.db import migrations
from django.apps import apps

def create_restrictions(apps_config, schema_editor):
    Restriction = apps.get_model('meals','Restriction')
    restrictions_list = [
        'vegan',
        'vegetarian',
        'pescatarian',
        'glutenfree',
        'lactose',
        'nuts',
    ]
    for restriction in restrictions_list:
        Restriction.objects.create(description=restriction)

class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0040_auto_20211027_1308'),
    ]

    operations = [
        migrations.RunPython(create_restrictions),
    ]
