# Generated by Django 3.2.3 on 2021-10-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0043_auto_20211027_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='glutenfree',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='lactose',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='nuts',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='pescatarian',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='vegan',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='vegetarian',
        ),
    ]
