# Generated by Django 3.2.3 on 2021-10-27 14:06

from django.db import migrations
from django.apps import apps

def swap_nuts_and_lactose(apps_config, schema_editor):
    Meal = apps.get_model('meals','Meal')
    Restriction = apps.get_model('meals','Restriction')

    nut_free_restriction = Restriction.objects.create(description="nutfree")
    lactose_free_restriction = Restriction.objects.create(description="lactosefree")

    nut_free_meals = Meal.objects.exclude(restrictions__description="nuts")

    for meal in nut_free_meals:
        meal.restrictions.add(nut_free_restriction)

    lactose_free_meals = Meal.objects.exclude(restrictions__description="lactose")

    for meal in lactose_free_meals:
        meal.restrictions.add(lactose_free_restriction)
    
    nut_restriction = Restriction.objects.get(description="nuts")
    lactose_restriction = Restriction.objects.get(description="lactose")

    nut_restriction.delete()
    lactose_restriction.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0044_auto_20211027_1338'),
    ]

    operations = [
        migrations.RunPython(swap_nuts_and_lactose),
    ]
