# Generated by Django 3.2.3 on 2021-11-01 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meals', '0045_auto_20211027_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restriction',
            name='description',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='weight',
            unique_together={('user', 'date')},
        ),
        migrations.RemoveField(
            model_name='weight',
            name='time',
        ),
    ]
