# Generated by Django 3.2.3 on 2021-11-01 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0046_auto_20211101_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(500)]),
        ),
    ]
