# Generated by Django 3.2.3 on 2021-11-04 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0047_alter_weight_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='lastMeal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lastMealViewed', to='meals.meal'),
        ),
    ]
