# Generated by Django 3.2.3 on 2022-02-08 00:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0048_alter_userinfo_lastmeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(600)]),
        ),
    ]
